- name: Configure Gaiad service
  template:
    src: gaiad.service.j2
    dest: /etc/systemd/system/gaiad.service
  notify: Reload systemd

- name: Enable and start gaiad service
  systemd:
    name: gaiad
    enabled: yes
    state: started
