- name: Configure Gaiad service
  template:
    src: gaiad.service.j2
    dest: /etc/systemd/system/gaiad.service

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start gaiad service
  systemd:
    name: gaiad
    enabled: yes