- name: Set node configuration
  shell: |
    gaiad config chain-id cosmoshub-4
    gaiad config node tcp://localhost:14957
  environment:
    GOROOT: /usr/local/go
    GOPATH: /home/cosmosuser/go
    PATH: "/usr/local/go/bin:/home/cosmosuser/go/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: cosmosuser

- name: Initialize Cosmos Hub node
  shell: gaiad init cosmos --chain-id cosmoshub-4
  environment:
    GOROOT: /usr/local/go
    GOPATH: /home/cosmosuser/go
    PATH: "/usr/local/go/bin:/home/cosmosuser/go/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: cosmosuser

- name: Create config directory
  file:
    path: /home/cosmosuser/.gaia/config
    state: directory
    owner: cosmosuser
    group: cosmosuser
    mode: '0755'
  become: yes

- name: Download genesis.json
  shell: curl -Ls https://github.com/cosmos/mainnet/raw/master/genesis/genesis.cosmoshub-4.json.gz | gunzip -c > /home/cosmosuser/.gaia/config/genesis.json

- name: Download addrbook.json
  shell: curl -Ls https://snapshots.lavenderfive.com/addrbooks/cosmoshub/addrbook.json > /home/cosmosuser/.gaia/config/addrbook.json

- name: Add seeds to config.toml
  shell: |
    seeds="ba3bacc714817218562f743178228f23678b2873@public-seed-node.cosmoshub.certus.one:26656,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:14956,20e1000e88125698264454a884812746c2eb4807@seeds.lavenderfive.com:14956,57a5297537b9b6ef8b105c08a8ad3f6ac452c423@seeds.goldenratiostaking.net:1618,c28827cb96c14c905b127b92065a3fb4cd77d7f6@seeds.whispernode.com:14956,8542cd7e6bf9d260fef543bc49e59be5a3fa9074@seed.publicnode.com:26656,400f3d9e30b69e78a7fb891f60d76fa3c73f0ecc@cosmoshub.rpc.kjnodes.com:11359,fe21dd474640247888fc7c4dce82da8da08a8bfd@seed-cosmos-hub-01.stakeflow.io:26656,11c6114a18f7b380e536b0bd17c031f4746e4ded@seed-node.mms.team:43656,87ccc1dcc0b846fc1623ab9a5ab55682e8e2ad2e@seed-cosmoshub.freshstaking.com:26656"
    sed -i -e "s|^seeds *=.*|seeds = \"$seeds\"|" /home/cosmosuser/.gaia/config/config.toml

- name: Set minimum gas price
  shell: sed -i -e "s|^minimum-gas-prices *=.*|minimum-gas-prices = \"0.005uatom\"|" /home/cosmosuser/.gaia/config/app.toml

- name: Set pruning
  shell: |
    sed -i \
      -e 's|^pruning *=.*|pruning = "custom"|' \
      -e 's|^pruning-keep-recent *=.*|pruning-keep-recent = "100"|' \
      -e 's|^pruning-keep-every *=.*|pruning-keep-every = "0"|' \
      -e 's|^pruning-interval *=.*|pruning-interval = "19"|' \
      /home/cosmosuser/.gaia/config/app.toml

- name: Set custom ports
  shell: |
    sed -i -e "s%^proxy_app = \"tcp://127.0.0.1:26658\"%proxy_app = \"tcp://127.0.0.1:14958\"%; s%^laddr = \"tcp://127.0.0.1:26657\"%laddr = \"tcp://127.0.0.1:14957\"%; s%^pprof_laddr = \"localhost:6060\"%pprof_laddr = \"localhost:14960\"%; s%^laddr = \"tcp://0.0.0.0:26656\"%laddr = \"tcp://0.0.0.0:14956\"%; s%^prometheus_listen_addr = \":26660\"%prometheus_listen_addr = \":14966\"%" /home/cosmosuser/.gaia/config/config.toml
    sed -i -e "s%^address = \"tcp://0.0.0.0:1317\"%address = \"tcp://0.0.0.0:14917\"%; s%^address = \":8080\"%address = \":14980\"%; s%^address = \"0.0.0.0:9090\"%address = \"0.0.0.0:14990\"%; s%^address = \"0.0.0.0:9091\"%address = \"0.0.0.0:14991\"%; s%:8545%:14945%; s%:8546%:14946%; s%:6065%:14965%" /home/cosmosuser/.gaia/config/app.toml

- name: Start gaiad service
  systemd:
    name: gaiad
    state: started
