- name: Check if Cosmovisor is installed
  command: /usr/local/go/bin/go list -m -versions github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor
  register: cosmovisor_check
  ignore_errors: yes
  changed_when: false
  environment:
    GOROOT: /usr/local/go
    GOPATH: /home/cosmosuser/go
    PATH: "/usr/local/go/bin:/home/cosmosuser/go/bin:{{ ansible_env.PATH }}"

- name: Install Cosmovisor if not installed or outdated
  ansible.builtin.command: /usr/local/go/bin/go install github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor@latest
  environment:
    GOROOT: /usr/local/go
    GOPATH: /home/cosmosuser/go
    PATH: "/usr/local/go/bin:/home/cosmosuser/go/bin:{{ ansible_env.PATH }}"
  when: cosmovisor_check.rc != 0 or 'cosmovisor' not in cosmovisor_check.stdout
  become: yes
  become_user: cosmosuser
