- name: Stop gaiad service
  systemd:
    name: gaiad
    state: stopped

- name: Backup priv_validator_state.json
  ansible.builtin.copy:
    src: /home/cosmosuser/.gaia/data/priv_validator_state.json
    dest: /home/cosmosuser/.gaia/priv_validator_state.json.backup
    remote_src: yes

- name: Remove existing data directory
  file:
    path: /home/cosmosuser/.gaia/data
    state: absent
  become: yes

- name: Install lz4
  apt:
    name: lz4
    state: present
    update_cache: yes

- name: Install aria2
  apt:
    name: aria2
    state: present
    update_cache: yes

- name: Check if snapshot file exists
  stat:
    path: /home/cosmosuser/cosmoshub_<snapshot ID>.tar.lz4
  register: snapshot_file

- name: Download snapshot if not already present
  ansible.builtin.get_url:
    url: https://snapshots.lavenderfive.com/snapshots/cosmoshub/cosmoshub_<snapshot ID>.tar.lz4
    dest: /home/cosmosuser/cosmoshub_<snapshot ID>.tar.lz4
    mode: '0644'
  when: not snapshot_file.stat.exists
  become: yes

- name: Extract snapshot if not already present
  ansible.builtin.unarchive:
    src: /home/cosmosuser/cosmoshub_<snapshot ID>.tar.lz4
    dest: /home/cosmosuser/.gaia
    remote_src: yes
    extra_opts:
      - --use-compress-program=lz4
  when: not snapshot_file.stat.exists
  become: yes

- name: Check if priv_validator_state.json.backup exists
  stat:
    path: /home/cosmosuser/.gaia/priv_validator_state.json.backup
  register: priv_validator_backup_file

- name: Create data directory if it does not exist
  file:
    path: /home/cosmosuser/.gaia/data
    state: directory
    owner: cosmosuser
    group: cosmosuser
    mode: '0755'
  become: yes

- name: Restore priv_validator_state.json if backup exists
  command: mv /home/cosmosuser/.gaia/priv_validator_state.json.backup /home/cosmosuser/.gaia/data/priv_validator_state.json
  become: yes
  when: priv_validator_backup_file.stat.exists

- name: Ensure correct ownership and permissions for .gaia directory
  file:
    path: /home/cosmosuser/.gaia
    state: directory
    owner: cosmosuser
    group: cosmosuser
    mode: '0755'
    recurse: yes
  become: yes

- name: Ensure correct ownership and permissions for data directory
  file:
    path: /home/cosmosuser/.gaia/data
    state: directory
    owner: cosmosuser
    group: cosmosuser
    mode: '0755'
    recurse: yes
  become: yes

- name: Start gaiad service
  systemd:
    name: gaiad
    state: started
