- name: Get public IP of the server
  ansible.builtin.uri:
    url: http://checkip.amazonaws.com
    return_content: yes
  register: public_ip

- name: Update external_address in config.toml
  ansible.builtin.lineinfile:
    path: /home/cosmosuser/.gaia/config/config.toml
    regexp: '^external_address = ".*"'
    line: 'external_address = "tcp://{{ public_ip.content.strip() }}:26656"'
  become: yes

# - name: Add persistent_peers to config.toml
#   lineinfile:
#     path: /home/cosmosuser/.gaia/config/config.toml
#     regexp: '^persistent_peers = ".*"'
#     line: 'persistent_peers = "id@ip:port,id@ip:port,id@ip:port"'
#   become_user: cosmosuser

- name: Restart gaiad service
  systemd:
    name: gaiad
    state: restarted
